sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bukeF4MPV/PQvuAjmV/BYzR9BYq9K/zaZoOoWI4sdST9IooYSZWmAWYZrOb9YwaaW7UY712ySMU4S/zqtmWlUoRK90O1HphXoIqHUhBwM57as/VrvZJNwgNvmyD5x/Ye6ISCO1uq8CHJlY2NIn+9AoRa23tSDfaAGFxLwJIxAvgCzxWAdFCU68zT6TPC+QrjJ5mGUD2x3sG2vCLAPC4hb7qVEUbq8zoXQFChu9Da3qSwbKlMqu/pk1BCm0QmgE0X/eooQTsW/RlIe8rHSpEouEimcMwGXe/x7iwGtgfhIop07PEGf/e9UQZDJnuoIxdMx18kgTuURCeHxwR8j3Ks0cmcot2Qy1mOjAm3Bwpg4LzCqgP11TeoTE61SPGY3hiZjRqp3N9TN3EinY49JpRZK3w0mk5pVodb7oovpOd9GncesIw//rxiplVtu++LM1ZclfYoFis0VnFXbr7cC4fgdHAs5LiAIB53NIyVzSL/rxIMZDFjEOl7vXMGYLg6cKVFDvdKjl/KYDpe8s3eHNfhcEAXFFrSkwnGpC2hjBbDjiUOI/w/U7Jvg2jEdJkVS71WOsyJPMWg/PJEe9wiwu7NikvyCcALlUYJKYLGul9oHYP2CbsaOk4uBa+M79kMMss4BK4uEHPQfm7M4uP8V2pmd9UAV5L6V5ZavQs7obqb1mM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Mother_3783
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy